@server = http://localhost:5216

get {{server}}/items

###
post {{server}}/items
Content-Type: application/json

{
    "Kaina": 10,
    "Kiekis": 50,
    "Pavadinimas": "Labai geras",
    "Aprasymas": "Labai grazus",
    "Tipas": ""
}

###

@id = 16298cb0-a1c4-4c67-bcaa-417722bdfb33
###
get {{server}}/items/{{id}}

###
delete {{server}}/items/c4636290-c8ca-419f-8dbd-4fc3e08241eb

###
PATCH {{server}}/items/{{id}}
Content-Type: application/json

{
    "kaina": 11,
    "kiekis": 50,
    "Pavadinimas": "Labai",
    "Aprasymas": "Labai grazus",
    "Tipas": 1
}

###

GET {{server}}/enums/types

###

GET {{server}}/Images/0c8a9690-69b6-4c2a-b496-4f4a15bd7592
Accept: */*
